name: 🚀 Deploy website on merge

env:
  METANET_FOLDER_DEV: dev.kaanpeeters.ch/

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - merged

run-name: Deploy to Host by @${{ github.actor }}
jobs:
  build-app:
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
      #
      #- name: Install types
      #  run: npm run supabaseLogin
      #  run: npm run types

      - name: Build SvelteKit App with Static Adapter
        run: npm run build
  deploy:
    name: 🎉 Deploy via FTP
    runs-on: ubuntu-latest
    uses: SamKirkland/FTP-Deploy-Action@v4.3.4
    with:
      server: ${{ secrets.METANET_SERVER }}
      username: ${{ secrets.METANET_LOGIN }}
      password: ${{ secrets.METANET_PASSWORD }}
      server-dir: $METANET_FOLDER_DEV
      local-dir: build/ #
